### ISSUE TITLE
STYLE: add pre-commit hooks

### ISSUE THREAD

**Issue by antoinecollet5** [antoinecollet5/nested_grid_plotter#6]
Add pre-commit hooks: https://github.com/pre-commit/pre-commit-hooks

```
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.3.0
  hooks:
    - id: check-json
    - id: check-yaml
    - id: end-of-file-fixer
    - id: trailing-whitespace
```
